### ISSUE TITLE
Migrate code base to Github repo

### ISSUE THREAD

**Issue by nthd3gr33** [MetaTypers/MetaTyping#1]
Why?
We need a code base

How?
- [x] clone existing code
- [x] change naming where needed
- [x] create dev branch 
- [x] push product branch to master

**Comment by JonathanWamsley** [comment]
To avoid headaches, I uploaded a more stable past version.

**Comment by nthd3gr33** [comment]
Excellent decision. Especially since I have a headache today 😆
