### ISSUE TITLE
Make the app compatible to windows cmd

### ISSUE THREAD

**Issue by JonathanWamsley** [MetaTypers/MetaTyping#12]
I know this exist. Investigate an elegant way of making the app windows compatible.

**Comment by nthd3gr33** [comment]
My suggestion: 
You may want to go straight to a web based app or plugin/extension. Consider how much development work each of the 3 would take, as well as their tradeoffs/benefits.

**Comment by JonathanWamsley** [comment]
#25 solved by including 'windows-curses;sys_platform=="win32"' in the requirements.txt file. A how to guide was also created for windows users that want to run the app.
