### ISSUE TITLE
"Running setup.py install for duckdb" stuck

### ISSUE THREAD

**Issue by baelesimon** [MetaTypers/MetaTyping#32]
Hey, I'm wondering what's wrong? I'm new to programming and I'd like to know if I did something wrong or if there is an actual problem. Thank you very much!

**Comment by baelesimon** [comment]
Nevermind. Just had to wait for 6-7 minutes hahahaha.

**Comment by JonathanWamsley** [comment]
yeah, I am considering just moving to sqlite but I would want to experiment with performances beforehand. Let me know if you face any problems or want any features 👌
