### ISSUE TITLE
 LICENSE.md needs to have <program properties> filled in

### ISSUE THREAD

**Issue by JonathanWamsley** [MetaTypers/MetaTyping#9]
## Why?
License needs to be filled to be more legit. Lines 634, 635, 655 all need to be filled out.
>     <one line to give the program's name and a brief idea of what it does.>
>     Copyright (C) <year>  <name of author>
>     <program>  Copyright (C) <year>  <name of author>

# How?
- [x] MetaTyping is a productivity application used to speed read and type text from any URL, clipboard or builtin drill.
- [x] For author, is it the organisation name or my name?
- [x] year
- [x] program = MetaTyping with no space I think

**Comment by nthd3gr33** [comment]
Nice catch. Will fix this soon.

**Comment by nthd3gr33** [comment]
Read lines 629-632 when you have time @JonathanWamsley. Will look into best practices for where we need to attach that text.

**Comment by JonathanWamsley** [comment]
I looked over that line. Its good to have a second pair of eyes @nthd3gr33 .

> To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

So:
>    MetaTyping is a productivity application used to speed read and type text
    Copyright (C) 2020 MetaTypers

will be copied to each .py file I am assuming. Should this be added to the current issue or should a new separate issue be created?

**Comment by nthd3gr33** [comment]
> will be copied to each .py file I am assuming.

Yes. Look at this [random example](https://github.com/tensorflow/models/blob/master/official/nlp/optimization.py). Different license, but you get the idea.

> Should this be added to the current issue or should a new separate issue be created?

Keep in this issue. Not sure what the best practice is for this though. Can you just have a template with that at the top when you are making new .py files? What about contributors? 🤔

**Comment by nthd3gr33** [comment]
Decision made:
@JonathanWamsley will put the small LICENSE template at the top of each .py file. Will discuss this issue again once we have other contributors. Closing this issue for now.
